FROM tomcat:9.0-jdk17

LABEL maintainer="Durga <durgaprasadsetti67@gmail.com>"

EXPOSE 8080

# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR generated by Maven
COPY target/maven-web-app.war /usr/local/tomcat/webapps/maven-web-app.war

# Start Tomcat
CMD ["catalina.sh", "run"]
